#!/bin/tcsh
#variables locales
#variables a modifier si necessaire
set workspace="ww"
set sources="src"
set doc="doc"
#fin initialisation variables


#debut
set rep_courant=`pwd`
cd ..
set rep_parent=`pwd`
#verification si on se trouve dans un repertoire $workspace
if ($rep_courant == $rep_parent/$workspace) then
	#verification de l'existance du repertoire ../$sources et ../$doc
	if (-e $sources && -e $doc) then
		cd $rep_courant
		echo Creation de la javadoc...
		set files=""
		#cherche recursivement les fichiers .java dans le repertoire ../$sources
		foreach i (`find ../$sources/ -name "*.java"`)
			set files="$files $i"
		end
		#commande de génération de javadoc
		#génère la doc dans le repertoire $doc
		javadoc -author -version -d ../$doc/$files
	else
		echo "Au moins un des repertoires ../$sources ou ../$doc n'existe pas"
	endif
else
	echo "La commande doit etre lancee depuis le repertoire $workspace du projet"
endif
#fin
